name: Create Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew clean build

      - name: Generate JAR
        run: ./gradlew fatJar

      - name: Extract release version
        id: extract_version
        run: |
          JAR_FILE=$(ls ./build/libs/c2k-*.jar | head -n 1)
          VERSION=$(echo "$JAR_FILE" | sed -E 's|.*/c2k-(.*)\.jar|\1|')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v${{ env.VERSION }}
          body: |
            Автоматический релиз с JAR-файлом.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/c2k-${{ env.VERSION }}.jar
          asset_name: c2k-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
